### ISSUE TITLE
Cannot read property 'sync' of undefined

### ISSUE THREAD

**Issue by dualcyclone** [prettier/prettier-eslint-cli#114]
We have setup `prettier-eslint` to help us with prettifying our project files as a precommit hook. I've just done a clean installation.

We are receiving the following error when executing prettier-eslint on our project files:

```bash
prettier-eslint-cli [ERROR]: There was an error formatting "--------.js": 
    TypeError: Cannot read property 'sync' of undefined
        at getPrettierConfig (/Users/--------/node_modules/prettier-eslint/dist/index.js:250:40)
        at format (/Users/--------/node_modules/prettier-eslint/dist/index.js:90:51)
        at MapSubscriber.project (/Users/--------/node_modules/prettier-eslint-cli/dist/format-files.js:276:55)
        at MapSubscriber._next (/Users/--------/node_modules/rxjs/operators/map.js:79:35)
        at MapSubscriber.Subscriber.next (/Users/--------/node_modules/rxjs/Subscriber.js:89:18)
        at AsyncSubject.Subject.next (/Users/--------/node_modules/rxjs/Subject.js:55:25)
        at AsyncSubject.complete (/Users/--------node_modules/rxjs/AsyncSubject.js:46:35)
        at handlerFn (/Users/--------/node_modules/rxjs/observable/BoundNodeCallbackObservable.js:193:33)
        at tryToString (fs.js:514:3)
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:502:12)
```

Dependencies installed as follows:
- prettier v1.7.4
- prettier-eslint v8.2.1
- prettier-eslint-cli v4.4.0
- RxJS v5.5.2

**Comment by dualcyclone** [comment]
I've discovered that this was a result of multiple node_module dependencies, which weren't properly cleared down. Closing
