### ISSUE TITLE
Add support for the --ignore-path CLI option

### ISSUE THREAD

**Issue by kripod** [prettier/prettier-eslint-cli#131]
Currently, when I try to use Prettier's [`--ignore-path`](https://prettier.io/docs/en/cli.html#ignore-path) CLI option with prettier-eslint, I come across many of the following error messages:

```
Ignored unknown option `{ "ignorePath": "./.gitignore" }`.
```

**Comment by thinkerdu** [comment]
Any progress on this? Really want to use `--ignore-path .gitignore`.

**Comment by Hauuguu** [comment]
Also would like to see this

**Comment by azz0r** [comment]
Any update on this? Currently we run this command
`prettier-eslint --write --ignore-path ./yarn`

I get these errors:
```
prettier-eslint-cli [ERROR]: There was an error formatting "/Sites/project/.yarn/releases/yarn-1.19.1.js": 
RangeError: Maximum call stack size exceeded
    at Object.onEndResult (/Sites/project/node_modules/common-tags/lib/stripIndentTransformer/stripIndentTransformer.js:21:40)
    at cb (/Sites/project/node_modules/common-tags/lib/TemplateTag/TemplateTag.js:161:50)
    at Array.reduce (<anonymous>)
    at TemplateTag.transformEndResult (/Sites/project/node_modules/common-tags/lib/TemplateTag/TemplateTag.js:163:32)
    at Object.TemplateTag.tag [as stripIndent] (/Sites/project/node_modules/common-tags/lib/TemplateTag/TemplateTag.js:54:20)
    at prettify (/Sites/project/node_modules/prettier-eslint/dist/index.js:155:41)
    at format (/Sites/project/node_modules/prettier-eslint/dist/index.js:149:20)
    at MapSubscriber.project (/Sites/project/node_modules/prettier-eslint-cli/dist/format-files.js:307:55)
    at MapSubscriber._next (/Sites/project/node_modules/rxjs/operators/map.js:79:35)
    at MapSubscriber.Subscriber.next (/Sites/project/node_modules/rxjs/Subscriber.js:93:18)
failure formatting 1 file with prettier-eslint
```
