### ISSUE TITLE
Failed to load plugin react: Cannot find module 'eslint-plugin-react'

### ISSUE THREAD

**Issue by bertho-zero** [prettier/prettier-eslint-cli#139]
I work in a monorepo, with eslint everything works perfectly but prettier-eslint does not find the plugins that are hoisted.

**Comment by bertho-zero** [comment]
`prettier-eslint-cli` ignore the current working directory, I need to `nohoist` `prettier-eslint-cli`.

**Comment by neutraali** [comment]
Pretty much stuck on missing plugins as well. It seems that providing `--eslint-config-path "./.eslintrc"` is working, causing the lib to start searching for missing plugins (such as `eslint-plugin-react`). However, it doesn't seem to work in conjunction with `--eslint-path "/type/any/path/here"`.

I'm trying to point `--eslint-path` at my global **ESLint** installation path (for ex. `/usr/local/lib/node_modules/eslint`) but I don't think it's being picked up by `eslint-prettier-cli`. Full error message details:

```
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.resolve (internal/module.js:18:19)
    at Plugins.load (/dev/example/node_modules/eslint/lib/config/plugins.js:106:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/dev/example/node_modules/eslint/lib/config/plugins.js:166:21)
    at loadFromDisk (/dev/example/node_modules/eslint/lib/config/config-file.js:501:35)
    at Object.load (/dev/example/node_modules/eslint/lib/config/config-file.js:559:20)
    at formatFilesFromArgv (/dev/example/node_modules/prettier-eslint-cli/dist/format-files.js:193:63)
    at Object.<anonymous> (/dev/example/node_modules/prettier-eslint-cli/dist/index.js:36:27)
    at Module._compile (module.js:660:30)
```
