### ISSUE TITLE
CI jobs are failing

### ISSUE THREAD

**Issue by bj00rn** [prettier/prettier-eslint-cli#151]
- `prettier-eslint-cli` version: N/A
- `prettier` version: N/A
- `eslint` version: N/A

Relevant code/config.

What you did: Create a bogus PR

What happened:

```
> prettier-eslint-cli@0.0.0-semantically-released start /home/travis/build/prettier/prettier-eslint-cli
> nps "validate"

[90mnps is executing[39m `[1mvalidate[22m` : [32mnode node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold,bgGreen.bold,bgBlack.bold" --prefix "[{name}]" --names "lint,build,test,test.cli" 'nps lint' 'nps build' 'nps test' 'nps test.cli'[39m
[42m[1m[test][22m[49m [90mnps is executing[39m `[1mtest[22m` : [32mnode node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=test jest --coverage[39m
[44m[1m[lint][22m[49m [90mnps is executing[39m `[1mlint[22m` : [32meslint . --cache[39m
[40m[1m[test.cli][22m[49m [90mnps is executing[39m `[1mtest.cli[22m` : [32mnode node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=test jest --config cli-test/jest.config.json[39m
[45m[1m[build][22m[49m [90mnps is executing[39m `[1mbuild[22m` : [32mnode node_modules/rimraf/bin.js dist && babel --copy-files --out-dir dist --ignore *.test.js,__mocks__ src[39m
[42m[1m[test][22m[49m [31mTypeError: (0 , (_jestUtil || _load_jestUtil(...)).validateCLIOptions) is not a function[39m
[42m[1m[test][22m[49m [31m    at buildArgv (/home/travis/build/prettier/prettier-eslint-cli/node_modules/jest-cli/build/cli/index.js:133:58)[39m
[42m[1m[test][22m[49m [31m    at Object.<anonymous> (/home/travis/build/prettier/prettier-eslint-cli/node_modules/jest-cli/build/cli/index.js:40:20)[39m
[42m[1m[test][22m[49m [31m    at Generator.next (<anonymous>)[39m
[42m[1m[test][22m[49m [31m    at step (/home/travis/build/prettier/prettier-eslint-cli/node_modules/jest-cli/build/cli/index.js:55:2669)[39m
[42m[1m[test][22m[49m [31m    at /home/travis/build/prettier/prettier-eslint-cli/node_modules/jest-cli/build/cli/index.js:55:2899[39m
[42m[1m[test][22m[49m [31m    at new Promise (<anonymous>)[39m
[42m[1m[test][22m[49m [31m    at Object.<anonymous> (/home/travis/build/prettier/prettier-eslint-cli/node_modules/jest-cli/build/cli/index.js:55:2580)[39m
[42m[1m[test][22m[49m [31m    at Object.run (/home/travis/build/prettier/prettier-eslint-cli/node_modules/jest-cli/build/cli/index.js:55:48)[39m
[42m[1m[test][22m[49m [31m    at Object.<anonymous> (/home/travis/build/prettier/prettier-eslint-cli/node_modules/jest-cli/bin/jest.js:13:25)[39m
[42m[1m[test][22m[49m [31m    at Module._compile (module.js:653:30)[39m
[42m[1m[test][22m[49m [31mThe script called "test" which runs "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=test jest --coverage" failed with exit code 1[39m https://github.com/kentcdodds/nps/blob/v5.9.4/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
[42m[1m[test][22m[49m [90m[2mnps test exited with code 1[22m[39m
[90m[2m-->[22m[39m [90m[2mSending SIGTERM to other processes..[22m[39m
[40m[1m[test.cli][22m[49m [31mTypeError: (0 , (_jestUtil || _load_jestUtil(...)).validateCLIOptions) is not a function[39m
[40m[1m[test.cli][22m[49m [31m    at buildArgv (/home/travis/build/prettier/prettier-eslint-cli/node_modules/jest-cli/build/cli/index.js:133:58)[39m
[40m[1m[test.cli][22m[49m [31m    at Object.<anonymous> (/home/travis/build/prettier/prettier-eslint-cli/node_modules/jest-cli/build/cli/index.js:40:20)[39m
[40m[1m[test.cli][22m[49m [31m    at Generator.next (<anonymous>)[39m
[40m[1m[test.cli][22m[49m [31m    at step (/home/travis/build/prettier/prettier-eslint-cli/node_modules/jest-cli/build/cli/index.js:55:2669)[39m
[40m[1m[test.cli][22m[49m [31m    at /home/travis/build/prettier/prettier-eslint-cli/node_modules/jest-cli/build/cli/index.js:55:2899[39m
[40m[1m[test.cli][22m[49m [31m    at new Promise (<anonymous>)[39m
[40m[1m[test.cli][22m[49m [31m    at Object.<anonymous> (/home/travis/build/prettier/prettier-eslint-cli/node_modules/jest-cli/build/cli/index.js:55:2580)[39m
[40m[1m[test.cli][22m[49m [31m    at Object.run (/home/travis/build/prettier/prettier-eslint-cli/node_modules/jest-cli/build/cli/index.js:55:48)[39m
[40m[1m[test.cli][22m[49m [31m    at Object.<anonymous> (/home/travis/build/prettier/prettier-eslint-cli/node_modules/jest-cli/bin/jest.js:13:25)[39m
[40m[1m[test.cli][22m[49m [31m    at Module._compile (module.js:653:30)[39m
[40m[1m[test.cli][22m[49m [31mThe script called "test.cli" which runs "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=test jest --config cli-test/jest.config.json" failed with exit code 1[39m https://github.com/kentcdodds/nps/blob/v5.9.4/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
[40m[1m[test.cli][22m[49m [90m[2mnps test.cli exited with code 1[22m[39m
[44m[1m[lint][22m[49m [90m[2mnps lint exited with code null[22m[39m
[45m[1m[build][22m[49m [90m[2mnps build exited with code null[22m[39m
[31mThe script called "validate" which runs "node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold,bgGreen.bold,bgBlack.bold" --prefix "[{name}]" --names "lint,build,test,test.cli" 'nps lint' 'nps build' 'nps test' 'nps test.cli'" failed with exit code 1[39m https://github.com/kentcdodds/nps/blob/v5.9.4/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcode[0m ELIFECYCLE
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35merrno[0m 1
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m prettier-eslint-cli@0.0.0-semantically-released start: `nps "validate"`
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Exit status 1
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m 
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Failed at the prettier-eslint-cli@0.0.0-semantically-released start script.
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m This is probably not a problem with npm. There is likely additional logging output above.
[0m
[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m A complete log of this run can be found in:
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     /home/travis/.npm/_logs/2019-02-25T09_05_05_865Z-debug.log
[0mtravis_time:end:07e22040:start=1551085503689823303,finish=1551085505877545302,duration=2187721999
[0K[31;1mThe command "npm start validate" exited with 1.[0m

travis_fold:start:cache.2
[0Kstore build cache
travis_time:start:124f042c
[0Ktravis_time:end:124f042c:start=1551085505881752322,finish=1551085505884557517,duration=2805195
[0Ktravis_time:start:08d6116a
[0K[32;1mchanges detected, packing new archive[0m
.
[32;1muploading PR.150/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--node-8.tgz[0m
[32;1mcache uploaded[0m
travis_time:end:08d6116a:start=1551085505888315456,finish=1551085514163864179,duration=8275548723
[0Ktravis_fold:end:cache.2
[0K

Done. Your build exited with 1.
```
Reproduction:

Create a bogus PR like so #150 

https://github.com/bj00rn/prettier-eslint-cli

Problem description:
CI Jobs fails for bogus PR

Suggested solution:

CI environment misconfigured?
Broken master branch?

**Comment by zimme** [comment]
I believe it's jest that needs updating... but I'm currently looking into fixing the filesystem mocks in `prettier-eslint` so I won't have time to look into anything else until that's fixed.

**Comment by bj00rn** [comment]
@zimme yup, created  #150  to bump jest-cli. However `test.cli` target still fails for test `accepts stdin of code`.  Any pointers and maybe i can help out?

**Comment by zimme** [comment]
It might have something to do with how this function runs `prettier-eslint-cli` and compares the output.

https://github.com/prettier/prettier-eslint-cli/blob/master/cli-test/tests/index.js#L134

Prettier started warning about not providing a filepath or parser explicitly a couple of versions back and that might have messed up the catching of the output here...

**Comment by bj00rn** [comment]
@zimme solved it. yep, seems prettier now expects `parser` args otherwise it throws no zero exitcode.

https://github.com/prettier/prettier-eslint-cli/pull/150/commits/cfc82cbfe8db29d10dbb54d44521f6fc1bd867a2
