### ISSUE TITLE
Missing dependency issue

### ISSUE THREAD

**Issue by geekyrajshri** [prettier/prettier-eslint-cli#155]
After upgrading to the latest version 5.0.0 I am getting the following error when I run the command for prettier-eslint.

```Error: Cannot find module 'indent-string'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)```

What am I missing in this new version

**Comment by zimme** [comment]
Are you using node 8 or higher?
