### ISSUE TITLE
Error: Cannot find module 'indent-string'

### ISSUE THREAD

**Issue by mvila** [prettier/prettier-eslint-cli#169]
- `prettier-eslint-cli` version: 5.0.0
- `prettier` version: 1.18.2
- `eslint` version: 6.1.0

Relevant code/config.

```javascript
// Doesn't matter
```

What you did:

```bash
./node_modules/.bin/prettier-eslint-check '**/*.js'
```

What happened:

```
Error: Cannot find module 'indent-string'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/mvila/dev/layrjs/deepr/node_modules/.registry.npmjs.org/prettier-eslint-cli/5.0.0/node_modules/prettier-eslint-cli/dist/format-files.js:36:44)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

Reproduction:

Run a fresh install of prettier-eslint-cli v5.0.0.

Problem description:

The 'indent-string' dependency is missing in production environment.

Suggested solution:

In `package.json`, move the 'indent-string' dependency from `"devDependencies"` to `"dependencies"`.

**Comment by rafaltrzop** [comment]
Running `$ prettier-eslint file.js` produces the same error. I think @mvila is right, `indent-string` package was moved to `devDependencies` by mistake in this commit https://github.com/prettier/prettier-eslint-cli/commit/4ef613e867713ffa37f7a9018f92131bdf0062e9 @zimme could you look into this?

**Comment by timruiterkamp** [comment]
@mvila Did you solve this? I just run into this issue after upgrading to yarn 2. In the yarn yaml file i can add the dependency but after that i get the issue:

```
export default function indentString(string, count = 1, options = {}) {
^^^^^^

SyntaxError: Unexpected token 'export'
```

**Comment by mvila** [comment]
Sorry @timruiterkamp, but I don't use prettier-eslint-cli anymore.

**Comment by timruiterkamp** [comment]
@mvila What is your alternative? I might have to switch too then, i am running a graphql codegen and use the prettier-eslint-cli to format the generated files

**Comment by mvila** [comment]
@timruiterkamp I don't use prettier-eslint-cli because I don't use ESLint anymore. I think that the combo Prettier + TypeScript (with the right settings) is good enough to ensure code quality.
