### ISSUE TITLE
eslint error: Configuration for rule "import/order" is invalid

### ISSUE THREAD

**Issue by williamoliveira** [prettier/prettier-eslint-cli#397]
- `prettier-eslint-cli` version: 5.0.1
- `prettier` version: 2.3.0
- `eslint` version: 7.26.0

Relevant code/config.

.eslintrc
```json
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint", "prettier"],
  "extends": [
    "eslint:recommended",
    "airbnb",
    "prettier"
  ],
  "env": {
    "browser": true,
    "es6": true,
    "node": true,
    "jest": true
  },
  "parserOptions": {
    "sourceType": "module"
  },
  "rules": {
    "prettier/prettier": "warn",
    "react/jsx-filename-extension": 0,
    "react/sort-comp": 0,
    "semi": 0,
    "import/extensions": "off",
    "jsx-a11y/href-no-hash": "off",
    "jsx-a11y/anchor-is-valid": ["warn", { "aspects": ["invalidHref"] }],
    "react/forbid-prop-types": "off",
    "react/require-default-props": "off",
    "react/jsx-props-no-spreading": "off",
    "prefer-destructuring": "off"
  }
}
```

.prettierrc
```json
{
  "printWidth": 80,
  "semi": false,
  "singleQuote": true,
  "trailingComma": "all"
}
```

What you did:
Ran
```javascript
prettier-eslint --write /home/william/projects/myprojec/packages/back/src/scripts/commands/helpers/savePermissions.js                                          

```

What happened:
```
$ prettier-eslint --write /home/william/projects/myprojec/packages/back/src/scripts/commands/helpers/savePermissions.js
prettier-eslint [ERROR]: eslint fix failed due to an eslint error
prettier-eslint-cli [ERROR]: There was an error formatting "/home/william/projects/myprojec/packages/back/src/scripts/commands/helpers/savePermissions.js": 
    Error: CLIOptions:
        Configuration for rule "import/order" is invalid:
        Value {"groups":[["builtin","external","internal"]],"warnOnUnassignedImports":false} should NOT have additional properties.

        at validateRuleOptions (/home/william/projects/myprojec/packages/back/node_modules/eslint/lib/shared/config-validator.js:132:19)
        at /home/william/projects/myprojec/packages/back/node_modules/eslint/lib/shared/config-validator.js:187:9
        at Array.forEach (<anonymous>)
        at validateRules (/home/william/projects/myprojec/packages/back/node_modules/eslint/lib/shared/config-validator.js:184:30)
        at validateConfigArray (/home/william/projects/myprojec/packages/back/node_modules/eslint/lib/shared/config-validator.js:312:9)
        at CascadingConfigArrayFactory._finalizeConfigArray (/home/william/projects/myprojec/packages/back/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:464:13)
        at CascadingConfigArrayFactory.getConfigArrayForFile (/home/william/projects/myprojec/packages/back/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:275:21)
        at CLIEngine.isPathIgnored (/home/william/projects/myprojec/packages/back/node_modules/eslint/lib/cli-engine/cli-engine.js:953:18)
        at CLIEngine.executeOnText (/home/william/projects/myprojec/packages/back/node_modules/eslint/lib/cli-engine/cli-engine.js:864:38)
        at eslintFix (/home/william/projects/myprojec-alt/node_modules/prettier-eslint-cli/node_modules/prettier-eslint/dist/index.js:158:32)
```

Problem description:
I've been getting this error with prettier-eslint, if I run prettier or eslint alone they work fine.

**Comment by williamoliveira** [comment]
Found the problem, there was some eslint plugins on lower versions inside a package of the monorepo
