### ISSUE TITLE
Error: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received ''

### ISSUE THREAD

**Issue by alendra1945** [prettier/prettier-eslint-cli#426]
Executing this command throws an exception!

- `prettier-eslint-cli` version: 5.0.1
- `prettier` version: prettier
- `eslint` version: 7.32.0

Command
`$ prettier-eslint --write 'src/**/*.{ts,tsx}'`

What happened:
Error Log:
```
jsxBracketSameLine is deprecated.
prettier-eslint [ERROR]: eslint fix failed due to an eslint error
prettier-eslint-cli [ERROR]: There was an error formatting "/home/alen/Adrena/Switch To RitelBuddy/ritelbuddy-2nd-gen/src/pages/_app.tsx": 
    TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received ''
        at createRequire (internal/modules/cjs/loader.js:1089:13)
        at Object.resolve (/home/alen/Adrena/Switch To RitelBuddy/ritelbuddy-2nd-gen/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:20)
        at Object.ModuleResolver.resolve (/home/alen/Adrena/Switch To RitelBuddy/ritelbuddy-2nd-gen/node_modules/@rushstack/eslint-patch/lib/modern-module-resolution.js:108:44)
        at ConfigArrayFactory._loadPlugin (/home/alen/Adrena/Switch To RitelBuddy/ritelbuddy-2nd-gen/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1017:39)
        at ConfigArrayFactory._loadPlugin (/home/alen/Adrena/Switch To RitelBuddy/ritelbuddy-2nd-gen/node_modules/@rushstack/eslint-patch/lib/modern-module-resolution.js:110:43)
        at /home/alen/Adrena/Switch To RitelBuddy/ritelbuddy-2nd-gen/node_modules/@eslint/eslintrc/lib/config-array-factory.js:908:33
        at Array.reduce (<anonymous>)
        at ConfigArrayFactory._loadPlugins (/home/alen/Adrena/Switch To RitelBuddy/ritelbuddy-2nd-gen/node_modules/@eslint/eslintrc/lib/config-array-factory.js:904:22)
        at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/alen/Adrena/Switch To RitelBuddy/ritelbuddy-2nd-gen/node_modules/@eslint/eslintrc/lib/config-array-factory.js:725:44)
        at _normalizeObjectConfigDataBody.next (<anonymous>)
```

**Comment by guimochila** [comment]
It was happened to me as well. I have removed `prettier-eslint-cli` and add `prettier`. It worked with ` prettier --write 'src/**/*.{ts,tsx}' `

**Comment by ownchoice** [comment]
Having the same problem with a Next.js project.

`eslint` and `next lint` both work just fine, but `prettier-eslint` (from `prettier-eslint-cli`) throws the error.

```
Error: Failed to load plugin '@typescript-eslint' declared in 'CLIOptions': The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received '' 
TypeError: Failed to load plugin '@typescript-eslint' declared in 'CLIOptions': The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received ''
    at new NodeError (node:internal/errors:371:5)
    at createRequire (node:internal/modules/cjs/loader:1277:13)
    at Object.resolve (d:\git\subfolder\project\web_prod\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2325:16)
    at Object.ModuleResolver.resolve (d:\git\subfolder\project\web_prod\node_modules\@rushstack\eslint-patch\lib\modern-module-resolution.js:201:44)
    at ConfigArrayFactory._loadPlugin (d:\git\subfolder\project\web_prod\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3376:33)
    at ConfigArrayFactory._loadPlugin (d:\git\subfolder\project\web_prod\node_modules\@rushstack\eslint-patch\lib\modern-module-resolution.js:203:43)
    at d:\git\subfolder\project\web_prod\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3267:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (d:\git\subfolder\project\web_prod\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3263:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (d:\git\subfolder\project\web_prod\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3063:44)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (d:\git\subfolder\project\web_prod\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3003:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.create (d:\git\subfolder\project\web_prod\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2798:16)
    at createCLIConfigArray (d:\git\subfolder\project\web_prod\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3608:47)
    at CascadingConfigArrayFactory.clearCache (d:\git\subfolder\project\web_prod\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3780:32)
    at new ESLint (d:\git\subfolder\project\web_prod\node_modules\eslint\lib\eslint\eslint.js:448:32)
    at Pge (c:\Users\onlyme\.vscode\extensions\rvest.vs-code-prettier-eslint-5.0.1\dist\extension.js:180:69)
    at c:\Users\onlyme\.vscode\extensions\rvest.vs-code-prettier-eslint-5.0.1\dist\extension.js:188:700
    at Lge (c:\Users\onlyme\.vscode\extensions\rvest.vs-code-prettier-eslint-5.0.1\dist\extension.js:180:1439)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by barroudjo** [comment]
Just realized my issue corresponds to the same problem as this one: https://github.com/prettier/prettier-eslint-cli/issues/434

**Comment by JounQin** [comment]
See https://github.com/prettier/prettier-eslint-cli/issues/434#issuecomment-1207331852

Otherwise, please provide a minimal but runnable reproduction.

https://antfu.me/posts/why-reproductions-are-required
